#!/usr/bin/perl

use strict;
use warnings;

use File::Path;

my ($file, $season_num, $episode_num) = @ARGV;
die "file required" unless defined $file;

my ($season_dir, $episode_str);

unless ($season_num && $episode_num) {
    my $episode = $season_num;
    die "episode requires" unless defined $episode;
    if ($episode =~ /^s(\d\d)e(\d\d)$/) {
        $season_num = $1;
        $episode_num = $2;
    } elsif ($episode =~ /^(\d{4})(-\d{2}-\d{2})/) {
        $season_dir = "Season $1";
        $episode_str = "$1$2";
    } elsif ($episode > 100) {
        $season_num = $episode / 100;
        $episode_num = $episode % 100;
    } else {
        die "Unknown format for $episode\n";
    }
}

my ($show_title, $episode_title) = split(/ - /, $file);
die "show_title not found for $file" unless $show_title;
die "episode_title not found for $file" unless $episode_title;

my $show_dir = $show_title;
$season_dir ||= sprintf("Season %02d", $season_num);
mkpath("$show_dir/$season_dir");

$episode_str ||= sprintf("s%02de%02d", $season_num, $episode_num);
my $plex_file = $show_title . ' - ' . $episode_str . ' - ' . $episode_title;
my $plex_path = "$show_dir/$season_dir/$plex_file";

print "$plex_path\n";
rename($file, $plex_path)
              or die "Rename $file to $plex_path failed: $!";
system('touch', ".$file");
