#!/usr/bin/env ruby

require 'fileutils'

file = ARGV.shift or raise "file required"

if ARGV.length == 2 then
  season_num, episode_num = *ARGV
elsif ARGV.length == 1 then
  episode = ARGV[0]
  if match = episode.match(/^s(\d\d)e(\d\d)$/) then
    season_num, episode_num = match.captures
  elsif match = episode.match(/^(\d{4})(-\d{2}-\d{2})/) then
    season_dir = "Season #{match[1]}"
    episode_str = match[0]
  elsif episode.to_i > 100 then
    season_num = episode.to_i / 100;
    episode_num = episode.to_i % 100;
  else
    raise "Unknown format for #{episode}"
  end
else
  raise "Wrong number of arguments"
end

show_title, episode_title = file.split(' - ')

series_dir = show_title
Dir.mkdir(series_dir) unless Dir.exists?(series_dir)

season_dir ||= 'Season ' + sprintf("%02d", season_num)
dir = series_dir + '/' + season_dir
Dir.mkdir(dir) unless Dir.exists?(dir)

episode_str ||= sprintf("s%02de%02d", season_num, episode_num)
plex_file = "#{show_title} - #{episode_str} - #{episode_title}"
plex_path = dir + '/' + plex_file

puts plex_path
File.rename(file, plex_path)

FileUtils.touch(".#{file}")
