#!/usr/bin/env ruby

require 'find'
require 'tempfile'

Find.find('.') do |path|
  if path =~ /.*\.mpg$/ && File.size?(path) && File.size?(path) > 4 then
    begin
      mp4_file = path.sub(/\.mpg$/, '.m4v')
      if ! File.exists?(mp4_file) then
        puts "convert #{path}"
        Dir::Tmpname.create(File.basename(mp4_file) + '.tmp.', File.dirname(path)) do |tmp_file|
          cmd = %Q{ffmpeg -nostdin -loglevel fatal -i "#{path}" -c:v libx264 -crf 23 -c:a copy -f mp4 "#{tmp_file}"}
          system(cmd) or raise "#{cmd} failed: #{$?}"
          File.rename(tmp_file, mp4_file)
          puts "create #{mp4_file}"
        end
      end
      puts "remove #{path}"
      File.unlink(path)
    rescue => e
      print "#{path} failed: #{e}"
    end
  end
end
